# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "bento/centos-6.7"

  # config.vm.hostname = ""
  config.vm.network "private_network", ip: "192.168.33.11"
  config.vm.network :forwarded_port, guest: 80, host: 8080

  config.vm.synced_folder "./www", "/var/www/html", create: true, owner: 'vagrant', group: 'vagrant', :mount_options => ['dmode=777', 'fmode=755']
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory","1028"]
    v.customize ["modifyvm", :id, "--cpus","1"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provision "shell", :path => "./provision/base.sh", :privileged => false
  config.vm.provision "shell", :path => "./provision/apache.sh", :privileged => false
  config.vm.provision "shell", :path => "./provision/mysql.sh", :privileged => false
  config.vm.provision "shell", :path => "./provision/php.sh", :privileged => false
  config.vm.provision "shell", :path => "./provision/etc.sh", :privileged => false
end
